dist: trusty
sudo: false

cache:
  directories:
     - ./node_modules

language: node_js
node_js:
  - "9.1"

install:
  - npm install
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
  - xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js

  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: changenode